"""message

Revision ID: e4ec6cefcb98
Revises: d6a845b8a15f
Create Date: 2026-04-05 15:03:13.293028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ec6cefcb98'
down_revision: Union[str, Sequence[str], None] = 'd6a845b8a15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('disabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disabled')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
